// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6mg1NVhcPvaM0FZC6KXb-kXIpj8qe3iI',
    appId: '1:652854796873:web:435c8eb2e14d22c88d1598',
    messagingSenderId: '652854796873',
    projectId: 'executive-assistant-de36b',
    authDomain: 'executive-assistant-de36b.firebaseapp.com',
    storageBucket: 'executive-assistant-de36b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Y3ORkSuqEifJceyJ-d-HGS6gL1ixyZk',
    appId: '1:652854796873:android:b6f5baf12d1932298d1598',
    messagingSenderId: '652854796873',
    projectId: 'executive-assistant-de36b',
    storageBucket: 'executive-assistant-de36b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnnYHd6nFqJEhKhFj7CPCpMN8TCgYO6FQ',
    appId: '1:652854796873:ios:212b2fb2fd0ecbeb8d1598',
    messagingSenderId: '652854796873',
    projectId: 'executive-assistant-de36b',
    storageBucket: 'executive-assistant-de36b.appspot.com',
    iosBundleId: 'com.example.executiveAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnnYHd6nFqJEhKhFj7CPCpMN8TCgYO6FQ',
    appId: '1:652854796873:ios:212b2fb2fd0ecbeb8d1598',
    messagingSenderId: '652854796873',
    projectId: 'executive-assistant-de36b',
    storageBucket: 'executive-assistant-de36b.appspot.com',
    iosBundleId: 'com.example.executiveAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6mg1NVhcPvaM0FZC6KXb-kXIpj8qe3iI',
    appId: '1:652854796873:web:e694df0a5e88acea8d1598',
    messagingSenderId: '652854796873',
    projectId: 'executive-assistant-de36b',
    authDomain: 'executive-assistant-de36b.firebaseapp.com',
    storageBucket: 'executive-assistant-de36b.appspot.com',
  );

}